language: node_js
version:
- stable
env:
  matrix:
    secure: j+Q0piS3Y6HskvUkkZeFL1rbxjui02GRC3aDSRnfgg3JGu2iKr60YFBGXiVTFE6Nv0nQwm9+J3z3rPsP9DGuGCw4jJoHKoa7vAZsF2cgaYAz1KwCwrWJPNHoMZOOyb7+AlgJ9qucEkNTgF1EXMrvTsGx7z7v1d7SzkM3XLrM2Y8Z6Rvk6zVynb6eZnBNBEk7TTVPl64KJzWzDBvKG1aEsEI8p3onhZ69i3EuKFS3jnpo6QuYGjWdn8aaTWK8UwPscoEiNwYc8Lvi0zf2zxibiAn7cpOgwGSARKMVr0Z9QufaUhkCPFv9YETKNixwcTjkJp0L3qFax4ce69iidEN5afoVJUJdB8c1M7qJbrk5E7YeuLuAwuZTHE5clpLH3QmOZCWDGlNBVQY5OGQBk9zzzU7KI4lkxmuERA+f27kX4sO9o0FMzNI44Qek5arTBCRT8ys54G5LGgKRDP+0JUsq7aIcjp2bmVnNSmZaifUEyleH/XZz227zqq7VU1XHLAz8UBjrRHd68+u91oasT/ZAdUsVKbcI95LKohch4J3NyceTMQIAzJNncu7j4sqoDed0F3Igb1zXQ+pOJ9DC37APo9x4IZw9Tw6s44DsRO1bo/ayILE+1UsMOf464XWY7HBW1pLtmf5TEHIbZm70z1mSOdmWz4ujk8TvXVqW240w2UI=
