language: node_js
version:
- stable
sudo: required
services:
- docker

env:
  global:
  - IMAGE_NAME=innablr_interview_app
  - secure: CJ9JLqYcMzyESXlrtzMmVcz0SVul1hyrUo2EKoxiLik0E1/ongn/Cw2WYh8f3k+kqdDj1+L5Byh4qxtpAoMVNtdVDYJ+PdBpS+ey0DeT99T85RVdafZULXbkzrUaNPVqCnyshbP6XaP5CtnyWdWpWnDEbm4XSW1pUWLoPhgaUS3PFNcePPNr0YnTajF6DS2ut56ldot8FLqBJrsturNUqg3FKQxxildz7Kjl4JMtF/1wA83Y0UMXuhMvPXsEhG20kuys8zt3hyq9JnUk0sXgcLDG5hkjtLwVOm0i+VVu7aTNAE+Zu5C9YaZr3q4VRJuE067c5k2LT2KDUz/mEz+/XnbIA0ymR5b8CI4K5VwVz0bobTsJfqhNDSuIXyk97xg4LHbVTuqC7w20jfrafITvN8GfgeE0cRyQPXYq/lT3t29CvkxXrp4/yClCBDysS9q3CNVR+gggudB7lEBuL3FgjDcp28Hpibx2q9zSuao6fLiFHXQ8UACgxu4D5YaPblI3I8ACTfB/wd8Rq6S3XmBxH7ISa7pWe4bKJMBJ9YCXDxv12hVVN2JpDwXKelLGUdsxTYpiPDs6jM9xDCoRaLDKPGjBzwJiuQY/eSwg7QLlJ13QHPX91D961tetZ3RFDJdzAwfSZIFOZOHTTBCs1qzvALEskVHAxMhEFM+Pb5rvBeY=
  - secure: X9pX+utZcxcIUbCfOYtTEm0qoUdRwODbBylFsP7yYRcMicUn/y+heDp4vvBF7FgHR6WG07IGIzw/W4Lb8TPFqPfzUkL0PZNFMNclBCBezdAyqpZqOFsGxhQxWsj9ePdmDQVa7AWBinj+CpD1v1TBeZVbtFGtn8VRL5w3a0BFDCuDvaFJkDuBc6He4PuYUbsZokCoolPbdn63ZGPTgJQOef33/j08qZtucBo1bknSGeDSPPHiPSpmC1GsHxsle17BOsX74xS2umYHGuUYMnZp+FhzfuYP3OhOftreu7QtEPiUn2QeJ0TtOvfaynGrm+VFmFXIK0kJpn25jv73+xQ/DKzjkXZmemHx9QY2gzpCSJw0lxq300jaZyE0D7smxLHH+uZWK0p77X/Q0zXFzxZkpXa59Jqm8W1G/xWgu0F2k40eaFdMsfo++qAdNTJg2wnLkpWDQNrhtqtmSMEyEbDc5F5p6wExLalOgfrEvwwAIektDnpSXZw1FlEb/NGIiqooPVaj50KUTA9mCRUi9ADHxSYZz+menIWRX+8TuWw6wHX5O+XszTaYUO4rIB1GqO3M1aUZhYFATrQ86Dj39h9Tw6FrTP+bX5KjLVK27S3w09LWPzZ9DY78p5PhFxnNm4EohB3AQm2x9bcRjpGLM1DnXofX3v4GaRu84YcVA67ofIU=

before_install:
  - gem install rake

stages:
  - build
  - test
  - push docker image
  - pull and deploy docker image

jobs:
  include:
    - stage: build
      if: branch = master AND env($TRAVIS_PULL_REQUEST) = false
      script: "make build"

    - stage: test
      script: echo "Run your test suite here"

    - stage: push docker image
      if: branch = master AND env($TRAVIS_PULL_REQUEST) = false
      script: "make push_image"
      # - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      #   make build_and_push; else echo "Build process created on push to master branch."; fi
      
    - stage: pull and deploy docker image
      if: branch = master AND env($TRAVIS_PULL_REQUEST) = false
      env: 
      - HOST=127.0.0.1
      script: "make pull_and_deploy"

